// internal/config/data/section.go
//
// Package data defines the configuration for data processing pipelines.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package data

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds data processing configuration
type Config struct {
	// Batch processing
	BatchSize     int           `mapstructure:"batch_size"`
	FlushInterval time.Duration `mapstructure:"flush_interval"`
	WorkerCount   int           `mapstructure:"worker_count"`
	MaxQueueSize  int           `mapstructure:"max_queue_size"`

	// Compression
	EnableCompression bool `mapstructure:"enable_compression"`

	// Processing modes
	EnableAsync      bool `mapstructure:"enable_async"`
	EnableParallel   bool `mapstructure:"enable_parallel"`
	EnableValidation bool `mapstructure:"enable_validation"`

	// Retention policies
	RetentionTraces   time.Duration `mapstructure:"retention_traces"`
	RetentionMetrics  time.Duration `mapstructure:"retention_metrics"`
	RetentionLogs     time.Duration `mapstructure:"retention_logs"`
	EnableAutoCleanup bool          `mapstructure:"enable_auto_cleanup"`
	CleanupInterval   time.Duration `mapstructure:"cleanup_interval"`
}

// Defaults returns reasonable default values for the Data Processing Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		BatchSize:         DEFAULT_BATCH_SIZE,
		FlushInterval:     DEFAULT_FLUSH_INTERVAL,
		WorkerCount:       DEFAULT_WORKER_COUNT,
		MaxQueueSize:      DEFAULT_QUEUE_SIZE,
		EnableCompression: DEFAULT_ENABLE_COMPRESSION,
		EnableAsync:       DEFAULT_ENABLE_ASYNC,
		EnableParallel:    DEFAULT_ENABLE_PARALLEL,
		EnableValidation:  DEFAULT_ENABLE_VALIDATION,
		RetentionTraces:   DEFAULT_RETENTION_TRACES,
		RetentionMetrics:  DEFAULT_RETENTION_METRICS,
		RetentionLogs:     DEFAULT_RETENTION_LOGS,
		EnableAutoCleanup: DEFAULT_ENABLE_AUTO_CLEANUP,
		CleanupInterval:   DEFAULT_CLEANUP_INTERVAL,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(DATA_PREFIX)

	// Batch processing validation
	base.RangeFNum(v, "batch_size", c.BatchSize, MIN_BATCH_SIZE, MAX_BATCH_SIZE, "")
	base.RangeFNum(v, "flush_interval", c.FlushInterval, MIN_FLUSH_INTERVAL, MAX_FLUSH_INTERVAL, "")
	base.RangeFNum(v, "worker_count", c.WorkerCount, MIN_WORKER_COUNT, MAX_WORKER_COUNT, "")
	base.RangeFNum(v, "max_queue_size", c.MaxQueueSize, MIN_QUEUE_SIZE, MAX_QUEUE_SIZE, "")

	// Retention validation
	base.RangeFNum(v, "retention_traces", c.RetentionTraces, MIN_RETENTION, MAX_RETENTION, "")
	base.RangeFNum(v, "retention_metrics", c.RetentionMetrics, MIN_RETENTION, MAX_RETENTION, "")
	base.RangeFNum(v, "retention_logs", c.RetentionLogs, MIN_RETENTION, MAX_RETENTION, "")

	// Cleanup validation (only if auto cleanup enabled)
	v.When(c.EnableAutoCleanup, func(v *base.Validator) {
		base.RangeFNum(v, "cleanup_interval", c.CleanupInterval, MIN_CLEANUP_INTERVAL, MAX_CLEANUP_INTERVAL, "")
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, DATA_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("data decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
