// internal/config/redis/section.go
//
// Package redis defines the configuration for Redis cache connections.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package redis

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds Redis cache configuration
type Config struct {
	Host               string        `mapstructure:"host"`
	Password           string        `mapstructure:"password"`
	Database           int           `mapstructure:"database"`
	MaxConnections     int           `mapstructure:"max_connections"`
	MaxIdleConnections int           `mapstructure:"max_idle_connections"`
	ConnectionTimeout  time.Duration `mapstructure:"connection_timeout"`
	DefaultTTL         time.Duration `mapstructure:"default_ttl"`

	// Connection pooling
	EnableConnectionPooling bool          `mapstructure:"enable_connection_pooling"`
	ConnectionMaxLifetime   time.Duration `mapstructure:"connection_max_lifetime"`
}

// Defaults returns reasonable default values for the Redis Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Host:                    DEFAULT_HOST,
		Password:                "",
		Database:                DEFAULT_DATABASE_INDEX,
		MaxConnections:          DEFAULT_MAX_CONNECTIONS,
		MaxIdleConnections:      DEFAULT_MAX_IDLE_CONNECTIONS,
		ConnectionTimeout:       DEFAULT_CONNECTION_TIMEOUT,
		DefaultTTL:              DEFAULT_DEFAULT_TTL,
		EnableConnectionPooling: DEFAULT_ENABLE_CONNECTION_POOLING,
		ConnectionMaxLifetime:   DEFAULT_CONNECTION_MAX_LIFETIME,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(REDIS_PREFIX)

	// Required fields
	base.NotEmpty(v, "host", c.Host)

	// Database index validation
	base.RangeFNum(v, "database", c.Database, MIN_DATABASE_INDEX, MAX_DATABASE_INDEX, "")

	// Connection pool validation
	base.RangeFNum(v, "max_connections", c.MaxConnections, MIN_MAX_CONNECTIONS, MAX_MAX_CONNECTIONS, "")
	base.RangeFNum(
		v,
		"max_idle_connections",
		c.MaxIdleConnections,
		MIN_MAX_IDLE_CONNECTIONS,
		MAX_MAX_IDLE_CONNECTIONS,
		"",
	)
	base.RangeFNum(v, "connection_timeout", c.ConnectionTimeout, MIN_CONNECTION_TIMEOUT, MAX_CONNECTION_TIMEOUT, "")
	base.RangeFNum(v, "default_ttl", c.DefaultTTL, MIN_DEFAULT_TTL, MAX_DEFAULT_TTL, "")

	// MaxIdleConnections must not exceed MaxConnections
	base.LTE(v, "max_idle_connections", c.MaxIdleConnections, c.MaxConnections, "max_connections")

	// Connection lifetime validation (only if pooling enabled)
	v.When(c.EnableConnectionPooling, func(v *base.Validator) {
		base.RangeFNum(
			v,
			"connection_max_lifetime",
			c.ConnectionMaxLifetime,
			MIN_CONNECTION_MAX_LIFETIME,
			MAX_CONNECTION_MAX_LIFETIME,
			"",
		)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, REDIS_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("redis decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
