package clickhouse

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds ClickHouse database configuration
type Config struct {
	Host               string        `mapstructure:"host"`
	HTTPHost           string        `mapstructure:"http_host"`
	Database           string        `mapstructure:"database"`
	Username           string        `mapstructure:"username"`
	Password           string        `mapstructure:"password"`
	MaxConnections     int           `mapstructure:"max_connections"`
	MaxIdleConnections int           `mapstructure:"max_idle_connections"`
	ConnectionTimeout  time.Duration `mapstructure:"connection_timeout"`
	EnableCompression  bool          `mapstructure:"enable_compression"`

	// Connection pooling
	EnableConnectionPooling bool          `mapstructure:"enable_connection_pooling"`
	ConnectionMaxLifetime   time.Duration `mapstructure:"connection_max_lifetime"`

	// Logging
	EnableQueryLogging bool `mapstructure:"enable_query_logging"`
}

// Defaults returns reasonable default values for the ClickHouse Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Host:                    DEFAULT_HOST,
		HTTPHost:                DEFAULT_HTTP_HOST,
		Database:                DEFAULT_DATABASE,
		Username:                DEFAULT_USERNAME,
		Password:                "",
		MaxConnections:          DEFAULT_MAX_CONNECTIONS,
		MaxIdleConnections:      DEFAULT_MAX_IDLE_CONNECTIONS,
		ConnectionTimeout:       DEFAULT_CONNECTION_TIMEOUT,
		EnableCompression:       DEFAULT_ENABLE_COMPRESSION,
		EnableConnectionPooling: DEFAULT_ENABLE_CONNECTION_POOLING,
		ConnectionMaxLifetime:   DEFAULT_CONNECTION_MAX_LIFETIME,
		EnableQueryLogging:      DEFAULT_ENABLE_QUERY_LOGGING,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(CLICKHOUSE_PREFIX)

	// Required fields
	base.NotEmpty(v, "host", c.Host)
	base.NotEmpty(v, "http_host", c.HTTPHost)
	base.NotEmpty(v, "database", c.Database)
	base.NotEmpty(v, "username", c.Username)

	// Connection pool validation
	base.RangeFNum(v, "max_connections", c.MaxConnections, MIN_MAX_CONNECTIONS, MAX_MAX_CONNECTIONS, "")
	base.RangeFNum(
		v,
		"max_idle_connections",
		c.MaxIdleConnections,
		MIN_MAX_IDLE_CONNECTIONS,
		MAX_MAX_IDLE_CONNECTIONS,
		"",
	)
	base.RangeFNum(v, "connection_timeout", c.ConnectionTimeout, MIN_CONNECTION_TIMEOUT, MAX_CONNECTION_TIMEOUT, "")

	// MaxIdleConnections must not exceed MaxConnections
	base.LTE(v, "max_idle_connections", c.MaxIdleConnections, c.MaxConnections, "max_connections")

	// Connection lifetime validation (only if pooling enabled)
	v.When(c.EnableConnectionPooling, func(v *base.Validator) {
		base.RangeFNum(
			v,
			"connection_max_lifetime",
			c.ConnectionMaxLifetime,
			MIN_CONNECTION_MAX_LIFETIME,
			MAX_CONNECTION_MAX_LIFETIME,
			"",
		)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, CLICKHOUSE_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("clickhouse decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
