// internal/config/circuitbreaker/section.go
//
// Package circuitbreaker defines the configuration for circuit breaker resilience patterns.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package circuitbreaker

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds circuit breaker resilience configuration
type Config struct {
	Enabled               bool            `mapstructure:"enabled"`
	Timeout               time.Duration   `mapstructure:"timeout"`
	MaxConcurrentRequests int             `mapstructure:"max_concurrent_requests"`
	RequestThreshold      int             `mapstructure:"request_threshold"`
	FailureRateThreshold  base.Percentage `mapstructure:"failure_rate_threshold"`
	ConsecutiveSuccesses  int             `mapstructure:"consecutive_successes"`
	SleepWindow           time.Duration   `mapstructure:"sleep_window"`
	HalfOpenMaxRequests   int             `mapstructure:"half_open_max_requests"`
}

// Defaults returns reasonable default values for the CircuitBreaker Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Enabled:               DEFAULT_ENABLED,
		Timeout:               DEFAULT_TIMEOUT,
		MaxConcurrentRequests: DEFAULT_CONCURRENT_REQUESTS,
		RequestThreshold:      DEFAULT_REQUEST_THRESHOLD,
		FailureRateThreshold:  DEFAULT_FAILURE_RATE_THRESHOLD,
		ConsecutiveSuccesses:  DEFAULT_CONSECUTIVE_SUCCESSES,
		SleepWindow:           DEFAULT_SLEEP_WINDOW,
		HalfOpenMaxRequests:   DEFAULT_HALF_OPEN_REQUESTS,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(CIRCUIT_BREAKER_PREFIX)

	// Timeout validation
	base.RangeFNum(v, "timeout", c.Timeout, MIN_TIMEOUT, MAX_TIMEOUT, "")

	// Concurrent request validation
	base.RangeFNum(
		v,
		"max_concurrent_requests",
		c.MaxConcurrentRequests,
		MIN_CONCURRENT_REQUESTS,
		MAX_CONCURRENT_REQUESTS,
		"",
	)

	// Request threshold validation
	base.RangeFNum(v, "request_threshold", c.RequestThreshold, MIN_REQUEST_THRESHOLD, MAX_REQUEST_THRESHOLD, "")

	// Failure rate threshold validation
	base.RangeFNum(
		v,
		"failure_rate_threshold",
		c.FailureRateThreshold.Value(),
		MIN_FAILURE_RATE_THRESHOLD.Value(),
		MAX_FAILURE_RATE_THRESHOLD.Value(),
		"%",
	)

	// Consecutive successes validation
	base.RangeFNum(
		v,
		"consecutive_successes",
		c.ConsecutiveSuccesses,
		MIN_CONSECUTIVE_SUCCESSES,
		MAX_CONSECUTIVE_SUCCESSES,
		"",
	)

	// Sleep window validation
	base.RangeFNum(v, "sleep_window", c.SleepWindow, MIN_SLEEP_WINDOW, MAX_SLEEP_WINDOW, "")

	// Half-open state validation
	base.RangeFNum(
		v,
		"half_open_max_requests",
		c.HalfOpenMaxRequests,
		MIN_HALF_OPEN_REQUESTS,
		MAX_HALF_OPEN_REQUESTS,
		"",
	)

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, CIRCUIT_BREAKER_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("circuitbreaker decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
