// internal/config/dlq/section.go
//
// Package dlq defines the configuration for dead letter queue handling.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package dlq

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds dead letter queue configuration
type Config struct {
	Enabled              bool           `mapstructure:"enabled"`
	QueueName            string         `mapstructure:"queue_name"`
	Region               base.AWSRegion `mapstructure:"region"`
	MaxMessageSize       base.Byte      `mapstructure:"max_message_size"`
	RetentionPeriod      time.Duration  `mapstructure:"retention_period"`
	QueueCapacity        int            `mapstructure:"queue_capacity"`
	LocalBufferSize      int            `mapstructure:"local_buffer_size"`
	EnableReprocessing   bool           `mapstructure:"enable_reprocessing"`
	ReprocessingCooldown time.Duration  `mapstructure:"reprocessing_cooldown"`
}

// Defaults returns reasonable default values for the DLQ Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Enabled:              DEFAULT_ENABLED,
		QueueName:            DEFAULT_QUEUE_NAME,
		Region:               DEFAULT_REGION,
		MaxMessageSize:       DEFAULT_MESSAGE_SIZE,
		RetentionPeriod:      DEFAULT_RETENTION_PERIOD,
		QueueCapacity:        DEFAULT_QUEUE_CAPACITY,
		LocalBufferSize:      DEFAULT_LOCAL_BUFFER_SIZE,
		EnableReprocessing:   DEFAULT_ENABLE_REPROCESSING,
		ReprocessingCooldown: DEFAULT_REPROCESSING_COOLDOWN,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(DLQ_PREFIX)

	// Queue name is required
	base.NotEmpty(v, "queue_name", c.QueueName)

	// Message size validation
	base.RangeFNum(v, "max_message_size", c.MaxMessageSize, MIN_MESSAGE_SIZE, MAX_MESSAGE_SIZE, "")

	// Retention validation
	base.RangeFNum(v, "retention_period", c.RetentionPeriod, MIN_RETENTION_PERIOD, MAX_RETENTION_PERIOD, "")

	// Queue capacity validation
	base.RangeFNum(v, "queue_capacity", c.QueueCapacity, MIN_QUEUE_CAPACITY, MAX_QUEUE_CAPACITY, "")

	// Local buffer validation
	base.RangeFNum(v, "local_buffer_size", c.LocalBufferSize, MIN_LOCAL_BUFFER_SIZE, MAX_LOCAL_BUFFER_SIZE, "")

	// Reprocessing cooldown validation (only if reprocessing enabled)
	v.When(c.EnableReprocessing, func(v *base.Validator) {
		base.RangeFNum(
			v,
			"reprocessing_cooldown",
			c.ReprocessingCooldown,
			MIN_REPROCESSING_COOLDOWN,
			MAX_REPROCESSING_COOLDOWN,
			"",
		)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, DLQ_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("dlq decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
