// internal/config/s3/section.go
//
// Package s3 defines the configuration for AWS S3 storage.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package s3

import (
	"fmt"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds S3 storage configuration
type Config struct {
	Region          base.AWSRegion `mapstructure:"region"`
	Bucket          string         `mapstructure:"bucket"`
	EndpointURL     string         `mapstructure:"endpoint_url"`
	AccessKeyID     string         `mapstructure:"access_key_id"`
	SecretAccessKey string         `mapstructure:"secret_access_key"`
	SessionToken    string         `mapstructure:"session_token"`
	PathPrefix      string         `mapstructure:"path_prefix"`
	ForcePathStyle  bool           `mapstructure:"force_path_style"`
	EnableSSE       bool           `mapstructure:"enable_sse"`
}

// Defaults returns reasonable default values for the S3 Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Region:          DEFAULT_REGION,
		Bucket:          "",
		EndpointURL:     "",
		AccessKeyID:     "",
		SecretAccessKey: "",
		SessionToken:    "",
		PathPrefix:      "",
		ForcePathStyle:  DEFAULT_FORCE_PATH_STYLE,
		EnableSSE:       DEFAULT_ENABLE_SSE,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(S3_PREFIX)

	// Bucket is required
	base.NotEmpty(v, "bucket", c.Bucket)

	// If credentials are provided, both must be present
	v.When(c.AccessKeyID != "" || c.SecretAccessKey != "", func(v *base.Validator) {
		base.NotEmpty(v, "access_key_id", c.AccessKeyID)
		base.NotEmpty(v, "secret_access_key", c.SecretAccessKey)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, S3_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("s3 decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
