// internal/config/monitoring/section.go
//
// Package monitoring defines the configuration for observability and monitoring.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package monitoring

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/app"
	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds monitoring and observability configuration
type Config struct {
	// Metrics
	EnableMetrics bool      `mapstructure:"enable_metrics"`
	MetricsPort   base.Port `mapstructure:"metrics_port"`
	MetricsPath   base.Path `mapstructure:"metrics_path"`

	// Tracing
	EnableTracing   bool   `mapstructure:"enable_tracing"`
	TracingEndpoint string `mapstructure:"tracing_endpoint"`

	// Jaeger distributed tracing
	EnableJaeger        bool            `mapstructure:"enable_jaeger"`
	JaegerServiceName   string          `mapstructure:"jaeger_service_name"`
	JaegerSamplingRate  base.Percentage `mapstructure:"jaeger_sampling_rate"`
	JaegerFlushInterval time.Duration   `mapstructure:"jaeger_flush_interval"`

	// Health checks
	HealthCheckPath base.Path `mapstructure:"health_check_path"`
}

// Defaults returns reasonable default values for the Monitoring Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		EnableMetrics:       DEFAULT_ENABLE_METRICS,
		MetricsPort:         DEFAULT_METRICS_PORT,
		MetricsPath:         DEFAULT_METRICS_PATH,
		EnableTracing:       DEFAULT_ENABLE_TRACING,
		TracingEndpoint:     "",
		EnableJaeger:        DEFAULT_ENABLE_JAEGER,
		JaegerServiceName:   app.DEFAULT_APP_NAME + base.COMPONENT_BACKEND,
		JaegerSamplingRate:  DEFAULT_JAEGER_SAMPLING_RATE,
		JaegerFlushInterval: DEFAULT_JAEGER_FLUSH_INTERVAL,
		HealthCheckPath:     DEFAULT_HEALTH_CHECK_PATH,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(MONITORING_PREFIX)

	// Port validation (only if metrics enabled)
	v.When(c.EnableMetrics, func(v *base.Validator) {
		base.RangeFNum(v, "metrics_port", c.MetricsPort, MIN_METRICS_PORT, MAX_METRICS_PORT, "")
		base.NotEmpty(v, "metrics_path", string(c.MetricsPath))
	})

	// Tracing endpoint validation (only if tracing enabled)
	v.When(c.EnableTracing, func(v *base.Validator) {
		base.NotEmpty(v, "tracing_endpoint", c.TracingEndpoint)
	})

	// Jaeger validation (only if Jaeger enabled)
	v.When(c.EnableJaeger, func(v *base.Validator) {
		base.NotEmpty(v, "jaeger_service_name", c.JaegerServiceName)
		base.RangeFNum(
			v,
			"jaeger_sampling_rate",
			c.JaegerSamplingRate.Value(),
			MIN_JAEGER_SAMPLING_RATE.Value(),
			MAX_JAEGER_SAMPLING_RATE.Value(),
			"%",
		)
		base.RangeFNum(
			v,
			"jaeger_flush_interval",
			c.JaegerFlushInterval,
			MIN_JAEGER_FLUSH_INTERVAL,
			MAX_JAEGER_FLUSH_INTERVAL,
			"",
		)
	})

	// Health check path validation
	base.NotEmpty(v, "health_check_path", string(c.HealthCheckPath))

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, MONITORING_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("monitoring decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
