# Local Development Environment Configuration
# Complete configuration for local development

app:
  name: "playback-backend"
  version: "1.0.0"
  description: "Distributed System Request Replayer and System Map"
  environment: "local"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # gin mode: debug, release, test
  trusted_proxies: []
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  max_header_bytes: 1048576  # 1MB

# Logging configuration
logging:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"
  enable_caller: true
  enable_stacktrace: true

# API configuration
api:
  version: "v1"
  prefix: "/api/v1"
  enable_cors: true
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 3600
  rate_limiting:
    enabled: true
    requests_per_second: 1000
    burst: 2000
  timeout: "30s"
  max_request_size: "10MB"

# Database connections
database:
  clickhouse:
    host: "localhost:9000"
    http_host: "localhost:8123"
    database: "telemetry"
    username: "admin"
    password: "admin123"
    max_connections: 10
    max_idle_connections: 5
    connection_timeout: "30s"
    read_timeout: "30s"
    write_timeout: "30s"
    enable_compression: true
    
  redis:
    host: "localhost:6379"
    password: "redis123"
    database: 0
    max_connections: 10
    max_idle_connections: 5
    connection_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"
    enable_cluster: false

# Message streaming
streaming:
  provider: "kinesis"  # kinesis, kafka, pubsub
  kinesis:
    region: "us-east-1"
    endpoint_url: "http://localhost:4566"  # LocalStack
    access_key_id: "test"
    secret_access_key: "test"
    streams:
      traces: "telemetry-traces"
      metrics: "telemetry-metrics"
      logs: "telemetry-logs"
    batch_size: 100
    flush_interval: "5s"
    max_retries: 3
    retry_delay: "1s"

# Data processing
processing:
  batch_size: 1000
  flush_interval: "5s"
  max_queue_size: 10000
  worker_count: 4
  retry_attempts: 3
  retry_delay: "1s"
  enable_compression: true
  compression_type: "gzip"

# Data retention policies (in days)
retention:
  traces: 7
  metrics: 30
  logs: 7
  service_dependencies: 90

# Caching configuration
cache:
  redis:
    enabled: true
    default_ttl: "5m"
    max_memory_policy: "allkeys-lru"
  application:
    enabled: true
    size: 1000
    ttl: "10m"

# Monitoring and observability
monitoring:
  enable_metrics: true
  enable_profiling: true
  enable_tracing: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  ready_endpoint: "/ready"
  profiling_endpoint: "/debug/pprof"
  
  jaeger:
    endpoint: ""
    service_name: "playback-backend"
    
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"

# Security settings
security:
  enable_auth: false  # Disabled for local development
  jwt:
    secret: "dev-secret-key"
    expiry: "24h"
    issuer: "playback-backend"
  cors:
    enabled: true
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Feature flags
features:
  replay:
    enabled: true
    max_concurrent_replays: 5
    replay_timeout: "2m"
  system_map:
    enabled: true
    update_interval: "10s"
    max_nodes: 500
  real_time_processing:
    enabled: true
    buffer_size: 5000
  batch_processing:
    enabled: true
    batch_interval: "30s"
  data_export:
    enabled: true
    formats: ["json", "csv"]
    max_export_size: "50MB"

# Performance tuning
performance:
  enable_compression: true
  compression_level: 3
  enable_connection_pooling: true
  max_idle_connections: 50
  connection_max_lifetime: "30m"
  enable_query_cache: true
  query_cache_size: "128MB"

# Development settings
development:
  enable_debug_endpoints: true
  enable_hot_reload: true
  mock_external_services: true
  seed_test_data: true
  enable_query_logging: true
  enable_request_logging: true

# Swagger documentation
swagger:
  enabled: true
  path: "/swagger"