// internal/config/testing/section.go
//
// Package testing defines the configuration for test environment behavior.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package testing

import (
	"fmt"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds test environment configuration
type Config struct {
	MockExternalServices bool `mapstructure:"mock_external_services"`
}

// Defaults returns reasonable default values for the Testing Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		MockExternalServices: DEFAULT_MOCK_EXTERNAL_SERVICES,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(TESTING_PREFIX)
	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, TESTING_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("testing decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
