// internal/config/features/section.go
//
// Package features defines the configuration for optional application features.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package features

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds optional feature configuration
type Config struct {
	// Replay feature: Re-process historical events
	EnableReplay     bool          `mapstructure:"enable_replay"`
	ReplayDuration   time.Duration `mapstructure:"replay_duration"`
	ReplayBufferSize base.Byte     `mapstructure:"replay_buffer_size"`

	// System map feature: Service dependency graph visualization
	EnableSystemMap    bool          `mapstructure:"enable_system_map"`
	MapRefreshInterval time.Duration `mapstructure:"map_refresh_interval"`
	MapMaxNodes        int           `mapstructure:"map_max_nodes"`
	MapMaxEdges        int           `mapstructure:"map_max_edges"`

	// Data export feature: Export telemetry data to files
	EnableDataExport bool                    `mapstructure:"enable_data_export"`
	ExportFormats    []base.DataExportFormat `mapstructure:"export_formats"`
	ExportMaxSize    base.Byte               `mapstructure:"export_max_size"`
}

// Defaults returns reasonable default values for the Features Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		EnableReplay:       DEFAULT_ENABLE_REPLAY,
		ReplayDuration:     DEFAULT_REPLAY_DURATION,
		ReplayBufferSize:   DEFAULT_REPLAY_BUFFER_SIZE,
		EnableSystemMap:    DEFAULT_ENABLE_SYSTEM_MAP,
		MapRefreshInterval: DEFAULT_MAP_REFRESH_INTERVAL,
		MapMaxNodes:        DEFAULT_MAP_NODES,
		MapMaxEdges:        DEFAULT_MAP_EDGES,
		EnableDataExport:   DEFAULT_ENABLE_DATA_EXPORT,
		ExportFormats:      DEFAULT_EXPORT_FORMATS,
		ExportMaxSize:      DEFAULT_EXPORT_SIZE,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(FEATURES_PREFIX)

	// Replay validation (only if enabled)
	v.When(c.EnableReplay, func(v *base.Validator) {
		base.RangeFNum(v, "replay_duration", c.ReplayDuration, MIN_REPLAY_DURATION, MAX_REPLAY_DURATION, "")
		base.RangeFNum(
			v,
			"replay_buffer_size",
			c.ReplayBufferSize,
			MIN_REPLAY_BUFFER_SIZE,
			MAX_REPLAY_BUFFER_SIZE,
			"bytes",
		)
	})

	// System map validation (only if enabled)
	v.When(c.EnableSystemMap, func(v *base.Validator) {
		base.RangeFNum(
			v,
			"map_refresh_interval",
			c.MapRefreshInterval,
			MIN_MAP_REFRESH_INTERVAL,
			MAX_MAP_REFRESH_INTERVAL,
			"",
		)
		base.RangeFNum(v, "map_max_nodes", c.MapMaxNodes, MIN_MAP_NODES, MAX_MAP_NODES, "")
		base.RangeFNum(v, "map_max_edges", c.MapMaxEdges, MIN_MAP_EDGES, MAX_MAP_EDGES, "")
	})

	// Data export validation (only if enabled)
	v.When(c.EnableDataExport, func(v *base.Validator) {
		v.Assert("export_formats", len(c.ExportFormats) > 0, "must specify at least one export format")
		base.RangeFNum(v, "export_max_size", c.ExportMaxSize, MIN_EXPORT_SIZE, MAX_EXPORT_SIZE, "bytes")
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, FEATURES_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("features decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
