// internal/config/grpc/section.go
//
// Package grpc defines the configuration for the GRPC Server.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package grpc

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds gRPC server configuration
type Config struct {
	Port                 base.Port     `mapstructure:"server_port"`
	MaxReceiveSize       base.Byte     `mapstructure:"max_receive_size"`
	MaxSendSize          base.Byte     `mapstructure:"max_send_size"`
	ConnectionTimeout    time.Duration `mapstructure:"max_connection_timeout"`
	RequestsPerSecond    int           `mapstructure:"max_requests_per_second"`
	RequestBurstCapacity int           `mapstructure:"max_request_burst_capacity"`
}

// Defaults returns reasonable default values for the GRPC Server Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{Port: DEFAULT_GRPC_SERVER_PORT,
		MaxReceiveSize:       DEFAULT_MAX_RECEIVE_SIZE,
		MaxSendSize:          DEFAULT_MAX_SEND_SIZE,
		ConnectionTimeout:    DEFAULT_CONNECTION_TIMEOUT,
		RequestsPerSecond:    DEFAULT_REQUESTS_PER_SECOND,
		RequestBurstCapacity: DEFAULT_REQUEST_BURST_CAPACITY,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {

	v := base.NewValidator(GRPC_PREFIX)

	base.RangeFNum(v, "port", c.Port, MIN_PORT, MAX_PORT, "")
	base.GT0FNum(v, "max_receive", c.MaxReceiveSize, "bytes")
	base.GT0FNum(v, "max_send", c.MaxSendSize, "bytes")
	base.RangeFNum(v, "connection_timeout", c.ConnectionTimeout, MIN_CONNECTION_TIMEOUT, MAX_CONNECTION_TIMEOUT, "")

	// RPS: Check if rate limiting is disabled
	base.RangeOrAllowed(v, "requests_per_second", c.RequestsPerSecond, MIN_RPS, MAX_RPS, "", RATE_LIMIT_DISABLED)

	// Couple RPS to Burst. i.e., rate limiting is disabled, don't add a burst capacity.
	v.When(c.RequestsPerSecond == RATE_LIMIT_DISABLED, func(v *base.Validator) {
		v.Assert("request_burst_capacity", c.RequestBurstCapacity == RATE_LIMIT_DISABLED,
			"must be 0 when %s=0 (got %d)", "requests_per_second", c.RequestBurstCapacity)
	})

	v.When(c.RequestsPerSecond > RATE_LIMIT_DISABLED, func(v *base.Validator) {
		// First, keep global guardrails:
		base.RangeFNum(v, "request_burst_capacity", c.RequestBurstCapacity, MIN_RBC, MAX_RBC, "")

		// Then add a *relationship* guardrail: bound burst by a multiple of RPS.
		maxByRPS := c.RequestsPerSecond * MAX_BURST_MULTIPLIER
		maxByRPS = max(MIN_RBC, maxByRPS) // safety
		v.Assert("request_burst_capacity", c.RequestBurstCapacity <= maxByRPS,
			"too large relative to %s: %d > %d (rps=%d)",
			"requests_per_second", c.RequestBurstCapacity, maxByRPS, c.RequestsPerSecond)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, GRPC_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("grpc decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
