// internal/config/kinesis/section.go
//
// Package kinesis defines the configuration for AWS Kinesis streaming.
//
// It consists of a Config struct and methods to resolve incoming key-values from a [config.Manager]
package kinesis

import (
	"fmt"
	"time"

	"github.com/jamesneb/playback-backend/internal/config/base"
	"github.com/jamesneb/playback-backend/internal/config/decodeutil"
	resolver "github.com/jamesneb/playback-backend/internal/config/propertyresolver"
)

// Config holds Kinesis streaming configuration
type Config struct {
	Region          base.AWSRegion `mapstructure:"region"`
	EndpointURL     string         `mapstructure:"endpoint_url"`
	AccessKeyID     string         `mapstructure:"access_key_id"`
	SecretAccessKey string         `mapstructure:"secret_access_key"`
	SessionToken    string         `mapstructure:"session_token"`

	// Stream names
	TracesStream  string `mapstructure:"traces_stream"`
	MetricsStream string `mapstructure:"metrics_stream"`
	LogsStream    string `mapstructure:"logs_stream"`

	// Batching
	BatchSize     int           `mapstructure:"batch_size"`
	FlushInterval time.Duration `mapstructure:"flush_interval"`

	// Retry behavior
	MaxRetries int           `mapstructure:"max_retries"`
	RetryDelay time.Duration `mapstructure:"retry_delay"`
}

// Defaults returns reasonable default values for the Kinesis Configuration.
// does not accept external config
// No external reads; callers overlay values via FromResolver
func Defaults() Config {
	return Config{
		Region:          DEFAULT_REGION,
		EndpointURL:     "",
		AccessKeyID:     "",
		SecretAccessKey: "",
		SessionToken:    "",
		TracesStream:    DEFAULT_TRACES_STREAM,
		MetricsStream:   DEFAULT_METRICS_STREAM,
		LogsStream:      DEFAULT_LOGS_STREAM,
		BatchSize:       DEFAULT_BATCH_SIZE,
		FlushInterval:   DEFAULT_FLUSH_INTERVAL,
		MaxRetries:      DEFAULT_RETRIES,
		RetryDelay:      DEFAULT_RETRY_DELAY,
	}
}

// validates the configuration generated by a propertyresolver
func (c Config) Validate() error {
	v := base.NewValidator(KINESIS_PREFIX)

	// Stream names are required
	base.NotEmpty(v, "traces_stream", c.TracesStream)
	base.NotEmpty(v, "metrics_stream", c.MetricsStream)
	base.NotEmpty(v, "logs_stream", c.LogsStream)

	// Batching validation
	base.RangeFNum(v, "batch_size", c.BatchSize, MIN_BATCH_SIZE, MAX_BATCH_SIZE, "")
	base.RangeFNum(v, "flush_interval", c.FlushInterval, MIN_FLUSH_INTERVAL, MAX_FLUSH_INTERVAL, "")

	// Retry validation
	base.RangeFNum(v, "max_retries", c.MaxRetries, MIN_RETRIES, MAX_RETRIES, "")
	base.RangeFNum(v, "retry_delay", c.RetryDelay, MIN_RETRY_DELAY, MAX_RETRY_DELAY, "")

	// If credentials are provided, both must be present
	v.When(c.AccessKeyID != "" || c.SecretAccessKey != "", func(v *base.Validator) {
		base.NotEmpty(v, "access_key_id", c.AccessKeyID)
		base.NotEmpty(v, "secret_access_key", c.SecretAccessKey)
	})

	return v.Err()
}

// overlays values from a [propertyresolver.PropertyResolver] onto Defaults and validates them
func FromResolver(r resolver.PropertyResolver) (Config, error) {
	cfg := Defaults()

	// Decodes values into mapstructure
	if err := decodeutil.DecodePrefixInto(r, KINESIS_PREFIX, &cfg); err != nil {
		return Config{}, fmt.Errorf("kinesis decode: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return Config{}, err
	}
	return cfg, nil
}
