#!/bin/bash

# AWS Integration Test Resource Setup Script
# Creates AWS resources required for integration testing

set -e

# Configuration
AWS_REGION=${AWS_REGION:-us-east-1}
TEST_S3_BUCKET=${TEST_S3_BUCKET:-playback-test-bucket-$(date +%s)}
TEST_KINESIS_TRACES_STREAM=${TEST_KINESIS_TRACES_STREAM:-test-telemetry-traces}
TEST_KINESIS_METRICS_STREAM=${TEST_KINESIS_METRICS_STREAM:-test-telemetry-metrics}
TEST_KINESIS_LOGS_STREAM=${TEST_KINESIS_LOGS_STREAM:-test-telemetry-logs}

echo "🚀 Setting up AWS resources for integration testing..."
echo "Region: $AWS_REGION"
echo "S3 Bucket: $TEST_S3_BUCKET"
echo "Kinesis Streams: $TEST_KINESIS_TRACES_STREAM, $TEST_KINESIS_METRICS_STREAM, $TEST_KINESIS_LOGS_STREAM"
echo

# Check AWS CLI is available and configured
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Please install AWS CLI."
    exit 1
fi

# Verify AWS credentials
echo "🔐 Verifying AWS credentials..."
aws sts get-caller-identity > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "❌ AWS credentials not configured. Please run 'aws configure' first."
    exit 1
fi
echo "✅ AWS credentials verified"

# Create S3 bucket
echo "📦 Creating S3 bucket: $TEST_S3_BUCKET"
if aws s3api head-bucket --bucket "$TEST_S3_BUCKET" 2>/dev/null; then
    echo "✅ S3 bucket already exists: $TEST_S3_BUCKET"
else
    if [ "$AWS_REGION" = "us-east-1" ]; then
        aws s3api create-bucket --bucket "$TEST_S3_BUCKET" --region "$AWS_REGION"
    else
        aws s3api create-bucket --bucket "$TEST_S3_BUCKET" --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi

    # Set bucket lifecycle to clean up test objects after 1 day
    cat > /tmp/lifecycle-policy.json << EOF
{
    "Rules": [
        {
            "ID": "DeleteTestObjects",
            "Status": "Enabled",
            "Expiration": {
                "Days": 1
            },
            "Filter": {
                "Prefix": "integration-test/"
            }
        },
        {
            "ID": "DeleteConcurrentTestObjects",
            "Status": "Enabled",
            "Expiration": {
                "Days": 1
            },
            "Filter": {
                "Prefix": "concurrent-test/"
            }
        }
    ]
}
EOF

    aws s3api put-bucket-lifecycle-configuration \
        --bucket "$TEST_S3_BUCKET" \
        --lifecycle-configuration file:///tmp/lifecycle-policy.json

    rm /tmp/lifecycle-policy.json
    echo "✅ S3 bucket created with lifecycle policy: $TEST_S3_BUCKET"
fi

# Function to create Kinesis stream
create_kinesis_stream() {
    local stream_name=$1
    echo "📊 Creating Kinesis stream: $stream_name"

    if aws kinesis describe-stream --stream-name "$stream_name" --region "$AWS_REGION" >/dev/null 2>&1; then
        echo "✅ Kinesis stream already exists: $stream_name"
    else
        aws kinesis create-stream \
            --stream-name "$stream_name" \
            --shard-count 1 \
            --region "$AWS_REGION"

        echo "⏳ Waiting for stream to become active: $stream_name"
        aws kinesis wait stream-exists \
            --stream-name "$stream_name" \
            --region "$AWS_REGION"

        echo "✅ Kinesis stream created and active: $stream_name"
    fi
}

# Create Kinesis streams
create_kinesis_stream "$TEST_KINESIS_TRACES_STREAM"
create_kinesis_stream "$TEST_KINESIS_METRICS_STREAM"
create_kinesis_stream "$TEST_KINESIS_LOGS_STREAM"

# Create environment file for integration tests
echo "📝 Creating integration test environment file..."
cat > test/integration/.env << EOF
# AWS Integration Test Configuration
# Generated by setup_aws_resources.sh on $(date)

# Enable integration tests
RUN_AWS_INTEGRATION_TESTS=true

# AWS Configuration
AWS_REGION=$AWS_REGION

# S3 Configuration
TEST_S3_BUCKET=$TEST_S3_BUCKET

# Kinesis Configuration
TEST_KINESIS_TRACES_STREAM=$TEST_KINESIS_TRACES_STREAM
TEST_KINESIS_METRICS_STREAM=$TEST_KINESIS_METRICS_STREAM
TEST_KINESIS_LOGS_STREAM=$TEST_KINESIS_LOGS_STREAM
EOF

echo "✅ Integration test environment file created: test/integration/.env"

echo
echo "🎉 AWS integration test resources setup completed!"
echo
echo "Resources created:"
echo "  S3 Bucket: $TEST_S3_BUCKET"
echo "  Kinesis Streams:"
echo "    - $TEST_KINESIS_TRACES_STREAM"
echo "    - $TEST_KINESIS_METRICS_STREAM"
echo "    - $TEST_KINESIS_LOGS_STREAM"
echo
echo "To run integration tests:"
echo "  cd test/integration && source .env && go test -v"
echo
echo "To cleanup resources:"
echo "  ./cleanup_aws_resources.sh"
echo
echo "⚠️  Note: S3 bucket has lifecycle policy to auto-delete test objects after 1 day"
echo "⚠️  Kinesis streams will incur charges. Remember to clean up when done."